# Generated by Django 6.0.5 on 2026-05-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Payé'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('STRIPE', 'Carte bancaire'), ('PAYPAL', 'PayPal'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('WAVE', 'Wave')], max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='gestion.studentapplication')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
