# Generated by Django 6.0.5 on 2026-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationEntry',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=5000000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GNF', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PENDING', 'En attente de validation'), ('REVIEWING', "En cours d'examen"), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée'), ('NEEDS_INFO', 'Informations complémentaires requises')], default='PENDING_PAYMENT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_payment_per_application'),
        ),
    ]
